<?php
$products = $this->getLoadedProductCollection();
$mode = $this->getMode();
$i = 0;
foreach ($products as $key => $_product) :?>
    <?php  if($i == 0):?>
<style>
    <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_RECOMMENDED_STYLING);?>
</style>

<table border="0" width="147" cellpadding="0" cellspacing="0" style='font-family:arial; border-collapse: collapse; font-size:12;'><tr>
    <?php endif;?>
    <?php
    //LIST MODE
    if($mode == 'list'){
        echo '</tr><tr>';
    }?>

    <td style="vertical-align: text-top; padding-right: 2px;">

        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="140" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" align="middle" /></a>

        <div class="product-name" align="center"><b><?php echo substr($_product->getName(), 0, 40);?></b></div>
        <div class="product-price" align="center"><?php echo $this->getPriceHtml($_product, true) ?></div>
        <div class="proudct-url" align="center"><a href="<?php echo $_product->getProductUrl();?>">View Now</a></div>
    </td>

    <?php if($i++ % 4 ==3 && $mode == 'grid') echo '</tr><tr>'?>

<?php endforeach;?>
<?php if( $i > 0) echo '</table>';

