<?php
$customer = $this->getNewCustomer();
?>

<body style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <table cellspacing="0" cellpadding="0" border="0" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">

                    <tr>
                        <td>
                            <table cellspacing="0" cellpadding="0" border="0" width="650">

                                <tbody>
                                <tr>
                                    <td>
                                        Use the following values when prompted to log in:
                                    </td>
                                </tr>
                                <tr>

                                    <td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; ">
                                        Username : <?php echo $customer->getEmail();?>
                                    </td>


                                </tr>
                                </tbody>
                            </table>
                        </td>

                    </tr>

                </table>

            </td>
        </tr>

        </table>
    </div>
</body>




