<?php  $_order = $this->getOrder() ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Email Preview</title>
</head>
<body>
<style type="text/css">
    body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
</style>
<body style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <table cellspacing="0" cellpadding="0" border="0" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <!-- [ header starts here] -->
                <table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">

                    <tr>
                        <td>
                            <?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
                                <h2 class="sub-title"><?php echo $this->__('Invoice #') ?><?php echo $_invoice->getIncrementId(); ?></h2>
                                <h3 class="table-caption"><?php echo $this->__('Items Invoiced') ?></h3>
                                <table cellspacing="0" cellpadding="0" border="0" width="650">
                                    <thead>
                                        <tr>
                                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;"><?php echo $this->__('Product Name');?></th>
                                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;"><?php echo $this->__('SKU');?></th>
                                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;"><?php echo $this->__('Price');?></th>
                                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;"><?php echo $this->__('Qty Invoiced');?></th>
                                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;"><?php echo $this->__('Subtotal');?></th>
                                        </tr>
                                        </thead>

                                        <?php $_items = $_invoice->getAllItems(); ?>
                                        <?php $_count = count($_items) ?>
                                        <?php foreach ($_items as $_item): ?>
                                            <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
                                            <tbody>
                                                <?php echo $this->getItemHtml($_item) ?>
                                            </tbody>
                                        <?php endforeach; ?>
                                        <tfoot>
                                            <?php //echo $this->getInvoiceTotalsHtml($_invoice)?>
                                        </tfoot>
                                </table>
                                <?php echo $this->getInvoiceCommentsHtml($_invoice)?>
                            <?php endforeach; ?>

                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>
</html>


