<?php

$productCollection = $this->getRecommendedProducts();
$listMode = $this->getMode();
$i = 0;
foreach ($productCollection as $key => $_product) :?>
    <?php $_product = Mage::getModel('catalog/product')->load($_product->getEntityId());?>
        <?php if($i == 0):?>
            <table border="0" bordercolor="#FFCC00" width="147" cellpadding="0" cellspacing="0" style='font-family:arial; border-collapse: collapse; font-size:12;'><tr>
        <?php endif;?>
        <?php
        //LIST MODE
        if($listMode == 'list'){
            echo '</tr><tr>';
        }?>

        <td style="vertical-align: text-top; padding-right: 2px;">


                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="140" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" align="middle" /></a>

            <div align="center"><b><?php echo substr($_product->getName(), 0, 40);?></b></div>

            <div align="center"><?php echo $this->getPriceHtml($_product, true);?></div>
            <div align="center"><a href="<?php echo $_product->getProductUrl();?>">View Now</a></div>
        </td>

    <?php if($i++ % 4 ==3 && $listMode == 'grid') echo '</tr><tr>'?>

<?php endforeach;?>

</table>


