<?php
$i = 0;
$helper = Mage::helper('connector/review');
$order = $this->getOrder();
$website = Mage::app()->getStore($order->getStoreId())->getWebsite();
$mode = $helper->getDisplayType($website);
$items = $this->filterItemsForReview($order->getAllVisibleItems(), $website);
?>

<?php if($items && is_array($items)): ?>
    <?php foreach ($items as $item) :?>
        <?php $_product = Mage::getModel('catalog/product')->load($item->getProductId()); ?>
        <?php  if($i == 0):?>
            <style>
                <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_STYLING);?>
            </style>

            <table border="0" width="147" cellpadding="0" cellspacing="0" style='font-family:arial; border-collapse: collapse; font-size:12;'><tr>
        <?php endif;?>
        <?php if($mode == 'list'):?>
            </tr><tr>
        <?php endif;?>

        <td style="vertical-align: text-top; padding-right: 2px;">
            <a href="<?php echo Mage::getUrl('review/product/list', array('id'=> $_product->getId())).$helper->getAnchor($website) ?>"
               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="140" height="135"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" align="middle" />
            </a>
            <div class="product-name" align="center"><b><?php echo substr($_product->getName(), 0, 40);?></b></div>
            <div class="proudct-url" align="center">
                <a href="<?php echo Mage::getUrl('review/product/list', array('id'=> $_product->getId())).$helper->getAnchor($website);?>">
                    <?php echo $this->__("Review Now") ?>
                </a>
            </div>
        </td>

        <?php if($i++ % 4 ==3 && $mode == 'grid'):?></tr><tr><?php endif;?>
    <?php endforeach;?>
    <?php if( $i > 0):?>
        </table>
    <?php endif;?>
<?php endif; ?>

